### PR TITLE
allow keyword "exists" as function name

### PR DESCRIPTION
**Pull request by phermsdorf**

### CODE REVIEW

**Comment by phermsdorf** [comment]
My change let's fail SelectAllColumnsCheckTest, but i don't know how to fix that ... :(

**Comment by felipebz** [comment]
That's tricky.

The test fails to check this query (from [here](https://github.com/felipebz/sonar-plsql/blob/d68fe8ddca21e525ba04d1b84b07b0d44bf0eeea/plsql-checks/src/test/resources/checks/select_all_columns.sql#L32-L35)):

```
select emp.sal
  into var
  from emp
 where exists (select * from e);
```

Before the change, the "exists (...)" was parsed as a EXISTS_EXPRESSION. With this change, it's now parsed as a METHOD_CALL.

image

To fix this test, in the [UNARY_EXPRESSION rule](https://github.com/felipebz/sonar-plsql/blob/d68fe8ddca21e525ba04d1b84b07b0d44bf0eeea/plsql-frontend/src/main/java/org/sonar/plugins/plsqlopen/api/PlSqlGrammar.java#L584) the EXISTS_EXPRESSION should be before MULTISET_EXPRESSION, then "exists (...)" won't be identified as a procedure/function call.

**Comment by phermsdorf** [comment]
Thanks again for the great support! I'm still not fully understanding why that worked but i'll look into that some more ;)

**Comment by felipebz** [comment]
:+1:

**Pull request merged**
