### PR TITLE
add "alter table" syntax - relates to #10

### PR DESCRIPTION
**Pull request by phermsdorf**
This time i tried to look at the IT tests more carefully ;) but I observed something weird:
a lot of parsing errors seem to go away with this change, but in some sources there seem to be new ones. 

E.g. in ut_package.pkb the parsing error moved from line 134 to line 122 but I don't understand why that 
happens:

```
   PROCEDURE ADD (
      suite_in            IN   INTEGER,
      package_in          IN   VARCHAR2,
      samepackage_in      IN   BOOLEAN := FALSE,
      prefix_in           IN   VARCHAR2 := NULL,
      dir_in              IN   VARCHAR2 := NULL,
      seq_in              IN   PLS_INTEGER := NULL,
      owner_in            IN   VARCHAR2 := NULL,
      add_tests_in        IN   BOOLEAN := FALSE,
      test_overloads_in   IN   BOOLEAN := FALSE
   )
   IS
      &start_ge_8_1 PRAGMA AUTONOMOUS_TRANSACTION; &end_ge_8_1
      v_owner    VARCHAR2 (30)                 := NVL (owner_in, USER);

```
The error moves from the &start_ge_8_ to the    PROCEDURE ADD line.

 When I extract the procedure creation into a separate test case in CreateProcedureTest the parsing error happens (as expected) at the &start_ge .. line.

Any hints on this?

Thanks!

### CODE REVIEW

**Comment by felipebz** [comment]
Hi, Peter.

Your change is ok, but it seems that the ITs are outdated. Maybe you defined ADD as a reserved keyword and changed it later.

From the [CI logs](https://travis-ci.org/felipebz/sonar-plsql/jobs/306263242#L2346):

```
11:11:53.044 ERROR - Unable to parse file: /home/travis/build/felipebz/sonar-plsql/its/sources/utPLSQL/source/ut_package.pkb
11:11:53.045 ERROR - Parse error at line 134 column 6:

  127: IN   VARCHAR2 := NULL,
  128:       seq_in              IN   PLS_INTEGER := NULL,
  129:       owner_in            IN   VARCHAR2 := NULL,
  130:       add_tests_in        IN   BOOLEAN := FALSE,
  131:       test_overloads_in   IN   BOOLEAN := FALSE
  132:    )
  133:    IS
  -->        &start_ge_8_1 PRAGMA AUTONOMOUS_TRANSACTION; &end_ge_8_1
  135:       v_owner    VARCHAR2 (30)                 := NVL (owner_in, USER);
  136:       v_id       ut_package.id%TYPE;
  137:       v_same     ut_package.
```

**Comment by phermsdorf** [comment]
Yes I did. Could you explain that a little more? 

I'm using clean verify to start the itegration build .... !?!?! ;)

**Comment by phermsdorf** [comment]
Got it. There dependencies between the "normal" build run and the integration build run. I wasn't aware of that.

**Comment by felipebz** [comment]
By the way, was you editing the plsql-ParsingError.json file manually? If so, I'm sorry for not giving exact instructions, it shouldn't be so hard.

The integration tests can be executed locally using: `mvn test -Pit -Dsonar.runtimeVersion=LATEST_RELEASE -Dmaven.test.redirectTestOutputToFile=false`.

When the ITs fail an updated .json with the issues will be located on its/ruling/target/actual. Then you can compared it to the json with the expected issues (its/ruling/src/test/resources/expected) and update the expectations accordingly (a.k.a. replace the expected file ;-) ).

**Comment by phermsdorf** [comment]
No, I found that myself ;) Thanks anyway. The point was to run the normal build before the integration tests and i probably missed that and thatswhy the report was not up-to-date.

**Pull request merged**
